USE [master]
ALTER DATABASE [TRN_CreditDeliveryDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [TRN_CreditDeliveryDB] FROM  DISK = N'E:\TRN_CreditDeliveryDB_20260113111438.BAK' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [TRN_CreditDeliveryDB] SET MULTI_USER

GO
